name: Golang Module Cache
author: Shopnap
description: Setup requested Golang version with module and build caching enabled.

inputs:
  go-version:
    description: The desired Go version to use.
    required: true
  private-key:
    description: The private key to use to access the private module's Github repositories.
    required: false

runs:
  using: composite
  steps:
    - name: Setup Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Determine OS Golang paths
      id: golang-path
      shell: bash
      run: |
        echo "::set-output name=build::$(go env GOCACHE)"
        echo "::set-output name=module::$(go env GOMODCACHE)"

    - name: "Setup private Go module key."
      if: ${{ inputs.private-key != '' }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.private-key }}

    - name: "Setup private Go module access."
      if: ${{ inputs.private-key != '' }}
      shell: bash
      run: git config --global url."ssh://git@github.com".insteadOf "https://github.com"

    - name: Setup Golang caches
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.golang-path.outputs.build }}
          ${{ steps.golang-path.outputs.module }}
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-golang-
