name: "Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-installation:
    name: Go ${{ matrix.go }} installation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.16", "1.15"]
    steps:
      - name: "Setup Go"
        uses: shopnap/setup-go@main
        with:
          go-version: ${{ matrix.go }}
      - name: "Verify Go installation"
        run: go version | grep -q ${{ matrix.go }}

  go-private-installation:
    name: Go ${{ matrix.go }} installation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.16", "1.15"]
    steps:
      - name: "Setup Go"
        uses: shopnap/setup-go@main
        with:
          go-version: ${{ matrix.go }}
          private-key: ${{ env.SSH_PRIVATE_KEY }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEMO_PRIVATE_KEY }}

      - name: "Verify Go installation"
        run: go version | grep -q ${{ matrix.go }}
